.TH CARBON-AGGREGATOR-CACHE 1
.SH NAME
carbon-aggregator-cache \- combines both carbon-aggregator and carbon-cache
.SH SYNOPSIS
.nf
.fam C
\fBcarbon-aggregator-cache\fP [options] start
.fam T
.fi
.SH DESCRIPTION
carbon-aggregator combines both carbon-aggregator and
carbon-cache. This is useful to reduce the resource and administration
overhead of running both daemons.
.PP
The options are described in the referenced manpages.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH SEE ALSO
\fBcarbon-aggregator\fP(1) \fBcarbon-cache\fP(1)
.SH AUTHOR
\fBcarbon-aggregator-cache\fP, created by Chris Davis.
.PP
This manual page was written by Alexandre Rossi <niol@zincube.net>, for
the Debian project (but may be used by others).
